# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formEditMaterial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formEditMaterialDialog(object):
    def setupUi(self, formEditMaterialDialog):
        formEditMaterialDialog.setObjectName("formEditMaterialDialog")
        formEditMaterialDialog.resize(350, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(formEditMaterialDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(formEditMaterialDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 2, 1, 1)
        self.buttonCancel = QtWidgets.QPushButton(self.frame_2)
        self.buttonCancel.setObjectName("buttonCancel")
        self.gridLayout_2.addWidget(self.buttonCancel, 2, 4, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboMaterial = QtWidgets.QComboBox(self.frame)
        self.comboMaterial.setObjectName("comboMaterial")
        self.comboMaterial.addItem("")
        self.comboMaterial.addItem("")
        self.comboMaterial.addItem("")
        self.gridLayout.addWidget(self.comboMaterial, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineNewMaterial = QtWidgets.QLineEdit(self.frame)
        self.lineNewMaterial.setStatusTip("")
        self.lineNewMaterial.setObjectName("lineNewMaterial")
        self.gridLayout.addWidget(self.lineNewMaterial, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 2, 4)
        self.buttonRename = QtWidgets.QPushButton(self.frame_2)
        self.buttonRename.setObjectName("buttonRename")
        self.gridLayout_2.addWidget(self.buttonRename, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_3 = QtWidgets.QFrame(formEditMaterialDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonRemove = QtWidgets.QPushButton(self.frame_3)
        self.buttonRemove.setObjectName("buttonRemove")
        self.gridLayout_3.addWidget(self.buttonRemove, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(formEditMaterialDialog)
        QtCore.QMetaObject.connectSlotsByName(formEditMaterialDialog)

    def retranslateUi(self, formEditMaterialDialog):
        _translate = QtCore.QCoreApplication.translate
        formEditMaterialDialog.setWindowTitle(_translate("formEditMaterialDialog", "Edit Material"))
        self.buttonCancel.setText(_translate("formEditMaterialDialog", "Cancel"))
        self.label.setText(_translate("formEditMaterialDialog", "Material"))
        self.comboMaterial.setItemText(0, _translate("formEditMaterialDialog", "HVS 80"))
        self.comboMaterial.setItemText(1, _translate("formEditMaterialDialog", "Art Carton"))
        self.comboMaterial.setItemText(2, _translate("formEditMaterialDialog", "Art Paper"))
        self.label_3.setText(_translate("formEditMaterialDialog", "Nama Material Baru"))
        self.lineNewMaterial.setPlaceholderText(_translate("formEditMaterialDialog", "masukan nama material baru"))
        self.buttonRename.setText(_translate("formEditMaterialDialog", "Rename"))
        self.buttonRemove.setText(_translate("formEditMaterialDialog", "Remove Material"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formEditMaterialDialog = QtWidgets.QDialog()
    ui = Ui_formEditMaterialDialog()
    ui.setupUi(formEditMaterialDialog)
    formEditMaterialDialog.show()
    sys.exit(app.exec_())
